### ISSUE TITLE
panic caused by query staking validator of module staking

### ISSUE THREAD

**Issue by tianxiataiping** [okex/okchain#66]
## Summary of Bug

command input:

```
$ okchaincli query staking validator okchain1g7znsf24w4jc3xfca88pq9kmlyjdare68lx3kq -o json --chain-id okchain --trust-node=false --node tcp://192.168.80.98:20157
```

panic:

```
Error initializing DB: resource temporarily unavailable


goroutine 1 [running]:
github.com/tendermint/tm-db.NewDB(0x4f3d58d, 0xa, 0x4f3c225, 0x9, 0xc000dbb860, 0x29, 0x0, 0x0)
	/Users/yangfan/go/pkg/mod/github.com/tendermint/tm-db@v0.2.0/db.go:72 +0x274
github.com/tendermint/tendermint/lite/proxy.NewVerifier(0x7ffeefbff7fd, 0x7, 0xc000dbb860, 0x29, 0x52d9880, 0xc000e20450, 0x52cfce0, 0x5b997c0, 0xa, 0xc000d52690, ...)
	/Users/yangfan/go/pkg/mod/github.com/okex/tendermint@v0.32.10-okchain/lite/proxy/verifier.go:30 +0x3aa
github.com/cosmos/cosmos-sdk/client/context.createVerifier(0x7ffeefbff81f, 0x19)
	/Users/yangfan/go/pkg/mod/github.com/okex/cosmos-sdk@v0.37.9-okchain1/client/context/context.go:139 +0x39e
github.com/cosmos/cosmos-sdk/client/context.NewCLIContextWithFrom(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/yangfan/go/pkg/mod/github.com/okex/cosmos-sdk@v0.37.9-okchain1/client/context/context.go:79 +0x55e
github.com/cosmos/cosmos-sdk/client/context.NewCLIContext(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/yangfan/go/pkg/mod/github.com/okex/cosmos-sdk@v0.37.9-okchain1/client/context/context.go:105 +0x8e
github.com/okex/okchain/x/staking/client/cli.GetCmdQueryValidator.func1(0xc000da4000, 0xc000d67e00, 0x1, 0x8, 0x0, 0x0)
	/Users/yangfan/go/src/github.com/okex/okchain/x/staking/client/cli/query.go:56 +0x5b
github.com/spf13/cobra.(*Command).execute(0xc000da4000, 0xc000d67d00, 0x8, 0x8, 0xc000da4000, 0xc000d67d00)
	/Users/yangfan/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:826 +0x460
github.com/spf13/cobra.(*Command).ExecuteC(0xc000d6a280, 0x483bfd0, 0xc000d6a280, 0x4f395e9)
	/Users/yangfan/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x2fb
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/yangfan/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
github.com/tendermint/tendermint/libs/cli.Executor.Execute(0xc000d6a280, 0x513baf0, 0x7, 0xc000c96060)
	/Users/yangfan/go/pkg/mod/github.com/okex/tendermint@v0.32.10-okchain/libs/cli/setup.go:89 +0x3c
main.main()
	/Users/yangfan/go/src/github.com/okex/okchain/cmd/okchaincli/main.go:78 +0x646

```

## Version
v0.10.0
## Steps to Reproduce

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by tianxiataiping** [comment]
No recurrence after redeployment
